GalaxyQuest/Models/ErrorViewModel.cs
namespace GalaxyQuest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GalaxyQuest/Models/Planet.cs
namespace GalaxyQuest.Models
{
    public class Planet
    {
        public string Name { get; set; }
        public long Population { get; set; }
    }
}

GalaxyQuest/Controllers/HomeController.cs
using GalaxyQuest.Models;
using GalaxyQuest.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GalaxyQuest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GalaxyQuest/Controllers/PlanetsController.cs
using GalaxyQuest.Services;
using Microsoft.AspNetCore.Mvc;
using GalaxyQuest.Models;
using GalaxyQuest.Interfaces;
using GalaxyQuest.Services;

namespace GalaxyQuest.Controllers
{
    public class PlanetsController : Controller
    {
        
        private readonly IPlanetService _planetService;

        public PlanetsController(ILogger<HomeController>logger, IPlanetService planetService)
        {
            
            _planetService = planetService;
        }
        public IActionResult Index()
        {
            var milkyWayPlanets = MilkyWayGalaxy.Planets;
          // var planets = await _planetService.GetPlanets();

           
            return View(milkyWayPlanets);
        }
    }
}

GalaxyQuest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Galaxy Quest</h1>
    <p>Dedicated to Exploring the Planets of Our Galaxy and Beyond!</a>.</p>
</div>

GalaxyQuest/Views/Planets/FarFarAwayIndex.cshtml
@model List<Planet>

<h2>Far Far Away Galaxy Planets</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Population</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var planet in Model)
        {
            <tr>
                <td>@planet.Name</td>
                <td>@planet.Population</td>
            </tr>
        }
    </tbody>
</table>

GalaxyQuest/Views/Planets/Index.cshtml
@model List<Planet>

<h2>Far Far Away Galaxy Planets</h2>


<h2>Milky Way Planets</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Population</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var planet in Model)
        {
            <tr>
                <td>@planet.Name</td>
                <td>@planet.Population</td>
            </tr>  
        }
    </tbody>
</table>

GalaxyQuest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GalaxyQuest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GalaxyQuest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GalaxyQuest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planets" asp-action="Index">Milky Way Planets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planets" asp-action="FarFarAwayIndex">Far Far Away Planets</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GalaxyQuest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>